
#数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mysql1911?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
#  resources:
#    static-locations:
#    - classpath:/resources/
#batis---mapper扫描路径
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
#打印日志
logging:
  level:
    com.st.dao: debug